# Generated by Django 3.2.23 on 2023-11-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('angry', 'Злой'), ('sad', 'Грустный'), ('neutral', 'Нейтральный')], max_length=20)),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроение',
            },
        ),
    ]
