# Generated by Django 5.1.1 on 2024-09-28 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_publishing', models.DateField(auto_created=True, verbose_name='Дата, когда статья была выложена')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Медицина', 'Медицина'), ('Психология', 'Психология'), ('Психотерапия', 'Психотерапия')], max_length=50, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Контент')),
                ('author', models.CharField(blank=True, max_length=500, null=True, verbose_name='Автор')),
                ('time_for_read', models.IntegerField(verbose_name='Время, необходимое для прочтения')),
                ('date', models.DateField(verbose_name='Дата написания')),
                ('literature', models.TextField(blank=True, null=True, verbose_name='Список литературы')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'Статья',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack_1', 'Перекус 1'), ('snack_2', 'Перекус 2')], max_length=50, verbose_name='Тип приёма пищи')),
                ('dish', models.TextField(blank=True, null=True, verbose_name='Пища')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='Жиры (г)')),
                ('proteins', models.FloatField(blank=True, null=True, verbose_name='Белки (г)')),
                ('carbs', models.FloatField(blank=True, null=True, verbose_name='Углеводы (г)')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='Калории')),
            ],
            options={
                'verbose_name': 'Пища',
                'verbose_name_plural': 'Пища',
            },
        ),
        migrations.CreateModel(
            name='CircleOfLifeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Окружение (%)')),
                ('family', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Семья (%)')),
                ('rest', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Отдых (%)')),
                ('comfort', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Комфорт (%)')),
                ('development', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Развитие (%)')),
                ('career', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Карьера (%)')),
                ('finance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Финансы (%)')),
                ('health', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Здоровье (%)')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Круг жизненного баланса',
                'verbose_name_plural': 'Круг жизненного баланса',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('meals', models.ManyToManyField(related_name='diets', to='main.meal', verbose_name='Приёмы пищи')),
            ],
            options={
                'verbose_name': 'Питание',
                'verbose_name_plural': 'Питание',
            },
        ),
        migrations.CreateModel(
            name='MedicalIndications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заболевание')),
                ('doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Врач (ФИО, контактные сведения)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото справки/Иного')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Пояснения')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Медицинские показания',
                'verbose_name_plural': 'Медицинские показания',
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_pulse', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний пульс')),
                ('type_of_activity', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Бокс', 'Бокс'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Теннис', 'Теннис'), ('Футбол', 'Футбол'), ('Бег', 'Бег'), ('Силовая тренировка', 'Силовая тренировка'), ('Йога', 'Йога'), ('Кардио-тренировка', 'Кардио-тренировака')], max_length=100, verbose_name='Тип активности')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('intensity', models.CharField(choices=[('Низкая', 'Низкая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя')], max_length=100, verbose_name='Интенсивность')),
                ('state_after', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состояние после тренировки:')),
                ('date', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Физическая нагрузка',
                'verbose_name_plural': 'Физические нагрузки',
                'db_table': 'Активность',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Psychotherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема обсуждения')),
                ('thoughts', models.TextField(blank=True, null=True, verbose_name='Мысли')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Психотерапия',
                'verbose_name_plural': 'Психотерапия',
            },
        ),
        migrations.CreateModel(
            name='RecordGratitudeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='Контент')),
                ('to_whom', models.CharField(max_length=100, verbose_name='Кому')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Запись Дневника Благодарности',
                'verbose_name_plural': 'Записи Дневника Благодарности',
                'db_table': 'Записи Дневника Благодарности',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Slumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество сна')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Продолжительность')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сон',
                'verbose_name_plural': 'Сон',
                'db_table': 'Сон',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=2.0, verbose_name='Количество (л)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Вода',
                'verbose_name_plural': 'Вода',
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Злой', 'Злой'), ('Грустный', 'Грустный'), ('Нейтральный', 'Нейтральный'), ('Игривый', 'Игривый'), ('Недовольный', 'Недовольный'), ('Довольный', 'Довольный'), ('Очень довольный', 'Очень довольный'), ('Агрессивный', 'Агрессивный'), ('Кокетливый', 'Кокетливый'), ('Грустный', 'Грустный'), ('Очень грустный', 'Очень грустный'), ('Ошарашенный', 'Ошарашенный'), ('В смятении', 'В сметянии'), ('В шоке', 'В шоке'), ('Радостный', 'Радостный')], max_length=20, verbose_name='Наименование:')),
                ('effort', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='На сколько сильной была эмоция')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='После чего вы ее испытали')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроение',
                'unique_together': {('author', 'date')},
            },
        ),
    ]
