# Generated by Django 3.2.23 on 2023-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_publishing', models.DateField(auto_created=True, verbose_name='Дата, когда статья была выложена')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('c1ategory', models.CharField(choices=[('Медицина', 'Медицина'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_for_read', models.IntegerField(verbose_name='Время, необходимое для прочтения')),
                ('date', models.DateField(verbose_name='Дата написания')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'Статья',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('angry', 'Злой'), ('sad', 'Грустный'), ('neutral', 'Нейтральный')], max_length=20, verbose_name='Наименование:')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроение',
            },
        ),
    ]
