# Generated by Django 3.2.23 on 2023-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c1ategory',
            field=models.CharField(choices=[('Психология', 'Психология'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
    ]
