# Generated by Django 5.1.1 on 2024-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Средняя', 'Средняя'), ('Низкая', 'Низкая'), ('Высокая', 'Высокая')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Бокс', 'Бокс'), ('Йога', 'Йога'), ('Силовая тренировка', 'Силовая тренировка'), ('Баскетбол', 'Баскетбол'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Футбол', 'Футбол'), ('Теннис', 'Теннис'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Бег', 'Бег')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
