# Generated by Django 3.2.23 on 2023-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231212_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='literature',
            field=models.TextField(blank=True, null=True, verbose_name='Список литературы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Медицина', 'Медицина'), ('Психотерапия', 'Психотерапия'), ('Семейные отношения', 'Семейные отношения'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
    ]
