# Generated by Django 3.2.23 on 2023-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Медицина', 'Медицина'), ('Психология', 'Психология'), ('Психотерапия', 'Психотерапия'), ('Семейные отношения', 'Семейные отношения')], max_length=50, verbose_name='Категория'),
        ),
    ]
