# Generated by Django 3.2.23 on 2023-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231212_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Психология', 'Психология'), ('Семейные отношения', 'Семейные отношения')], max_length=50, verbose_name='Категория'),
        ),
    ]
