# Generated by Django 3.2.23 on 2023-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия'), ('Психология', 'Психология'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
    ]
