# Generated by Django 3.2.23 on 2023-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Психология', 'Психология'), ('Семейные отношения', 'Семейные отношения')], max_length=50, verbose_name='Категория'),
        ),
    ]
