# Generated by Django 3.2.23 on 2023-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordGratitudeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('to_whom', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись Дневника Благодарности',
                'verbose_name_plural': 'Записи Дневника Благодарности',
                'db_table': 'Записи Дневника Благодарности',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Психология', 'Психология'), ('Семейные отношения', 'Семейные отношения'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
    ]
