# Generated by Django 3.2.23 on 2023-12-15 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20231215_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordgratitudejournal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Семейные отношения', 'Семейные отношения'), ('Медицина', 'Медицина'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recordgratitudejournal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
