# Generated by Django 3.2.23 on 2023-12-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20231215_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Семейные отношения', 'Семейные отношения'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recordgratitudejournal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recordgratitudejournal',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='recordgratitudejournal',
            name='to_whom',
            field=models.CharField(max_length=100, verbose_name='Кому'),
        ),
    ]
