# Generated by Django 3.2.23 on 2023-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231216_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='slumber',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психология', 'Психология'), ('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
    ]
