# Generated by Django 3.2.23 on 2023-12-23 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20231223_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психология', 'Психология'), ('Медицина', 'Медицина'), ('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='slumber',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='slumber',
            name='quality',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество сна'),
        ),
    ]
