# Generated by Django 3.2.23 on 2023-12-23 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20231223_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Медицина', 'Медицина'), ('Психотерапия', 'Психотерапия'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='slumber',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Продолжительность'),
        ),
    ]
