# Generated by Django 3.2.23 on 2023-12-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231223_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_pulse', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний пульс')),
                ('type_of_activity', models.CharField(choices=[('Бокс', 'Бокс'), ('Бег', 'Бег'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Баскетбол', 'Баскетбол'), ('Йога', 'Йога'), ('Силовая тренировка', 'Силовая тренировка'), ('Футбол', 'Футбол'), ('Теннис', 'Теннис'), ('Кардио-тренировка', 'Кардио-тренировака')], max_length=100, verbose_name='Тип активности')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('intensity', models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], max_length=100, verbose_name='Интенсивность')),
                ('stateAfter', models.CharField(max_length=250, verbose_name='Состояние после тренировки:')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Физическая нагрузка',
                'verbose_name_plural': 'Физические нагрузки',
                'db_table': 'Активность',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психотерапия', 'Психотерапия'), ('Семейные отношения', 'Семейные отношения'), ('Психология', 'Психология'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
    ]
