# Generated by Django 3.2.23 on 2023-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20231224_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalactivity',
            old_name='stateAfter',
            new_name='state_after',
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Бег', 'Бег'), ('Йога', 'Йога'), ('Теннис', 'Теннис'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Футбол', 'Футбол'), ('Силовая тренировка', 'Силовая тренировка'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Бокс', 'Бокс')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
