# Generated by Django 3.2.23 on 2023-12-23 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231224_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('angry', 'Злой'), ('sad', 'Грустный'), ('neutral', 'Нейтральный')], max_length=20, verbose_name='Наименование:')),
                ('effort', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='На сколько сильной была эмоция')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.TextField(verbose_name='После чего вы ее испытали')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроение',
            },
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия'), ('Психология', 'Психология'), ('Медицина', 'Медицина')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Средняя', 'Средняя'), ('Высокая', 'Высокая'), ('Низкая', 'Низкая')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Бокс', 'Бокс'), ('Силовая тренировка', 'Силовая тренировка'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Теннис', 'Теннис'), ('Баскетбол', 'Баскетбол'), ('Йога', 'Йога'), ('Бег', 'Бег'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Футбол', 'Футбол')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
