# Generated by Django 3.2.23 on 2023-12-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20231224_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Высокая', 'Высокая'), ('Средняя', 'Средняя')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='state_after',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Состояние после тренировки:'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Спортивная ходьба', 'Спортивная ходьба'), ('Бокс', 'Бокс'), ('Теннис', 'Теннис'), ('Баскетбол', 'Баскетбол'), ('Йога', 'Йога'), ('Силовая тренировка', 'Силовая тренировка'), ('Бег', 'Бег'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Футбол', 'Футбол')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
