# Generated by Django 3.2.23 on 2023-12-25 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20231225_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivity',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Медицина', 'Медицина'), ('Психотерапия', 'Психотерапия'), ('Семейные отношения', 'Семейные отношения'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Силовая тренировка', 'Силовая тренировка'), ('Баскетбол', 'Баскетбол'), ('Бег', 'Бег'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Йога', 'Йога'), ('Теннис', 'Теннис'), ('Футбол', 'Футбол'), ('Бокс', 'Бокс'), ('Кардио-тренировка', 'Кардио-тренировака')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
