# Generated by Django 3.2.23 on 2023-12-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20231225_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Психология', 'Психология'), ('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Семейные отношения', 'Семейные отношения')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='title',
            field=models.CharField(choices=[('Злой', 'Злой'), ('Грустный', 'Грустный'), ('Нейтральный', 'Нейтральный'), ('Игривый', 'Игривый'), ('Недовольный', 'Недовольный'), ('Довольный', 'Довольный'), ('Очень довольный', 'Очень довольный'), ('Агрессивный', 'Агрессивный'), ('Кокетливый', 'Кокетливый'), ('Грустный', 'Грустный'), ('Очень грустный', 'Очень грустный'), ('Ошарашенный', 'Ошарашенный'), ('В смятении', 'В сметянии'), ('В шоке', 'В шоке'), ('Радостный', 'Радостный')], max_length=20, verbose_name='Наименование:'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Высокая', 'Высокая'), ('Средняя', 'Средняя'), ('Низкая', 'Низкая')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Бокс', 'Бокс'), ('Бег', 'Бег'), ('Йога', 'Йога'), ('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Силовая тренировка', 'Силовая тренировка'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Теннис', 'Теннис')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
