# Generated by Django 3.2.23 on 2023-12-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20231226_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Семейные отношения', 'Семейные отношения'), ('Психотерапия', 'Психотерапия'), ('Медицина', 'Медицина'), ('Психология', 'Психология')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='После чего вы ее испытали'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='intensity',
            field=models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], max_length=100, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='type_of_activity',
            field=models.CharField(choices=[('Бег', 'Бег'), ('Бокс', 'Бокс'), ('Кардио-тренировка', 'Кардио-тренировака'), ('Спортивная ходьба', 'Спортивная ходьба'), ('Баскетбол', 'Баскетбол'), ('Силовая тренировка', 'Силовая тренировка'), ('Теннис', 'Теннис'), ('Йога', 'Йога'), ('Футбол', 'Футбол')], max_length=100, verbose_name='Тип активности'),
        ),
    ]
